<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <ProjectReference Include="../Baseline.Sample.Domain/Baseline.Sample.Domain.csproj" />
  </ItemGroup>
</Project>
