<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../Core/Baseline.Sample.Application/Baseline.Sample.Application.csproj" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
